### ISSUE TITLE
Explain of `CoreState::CalcQSmallAngleApprox`

### ISSUE THREAD

**Issue by extr15** [aau-cns/mars_lib#2]
Hi authors, thanks for your work!
I read the code and it is clear and well documented.
There is a function `CoreState::CalcQSmallAngleApprox` in `core_state_calc_q.cpp`, could you explain how to generate it?

**Comment by Chris-Bee** [comment]
Hello extr15,

Thank you for your feedback and your question. We will add this to the documentation soon. CoreState::CalcQSmallAngleApprox() calculates the process noise Q as follows:

![](https://latex.codecogs.com/svg.latex?\textbf{P}_{n+1}=\textbf{F}_x\textbf{P}\textbf{F}_x^\mathsf{T}+\textbf{Q})
![](https://latex.codecogs.com/svg.latex?\textbf{Q}=\int_{0}^{\Delta{}t}\textbf{F}_x\textbf{F}_n\textbf{P}\textbf{F}_n^\mathsf{T}\textbf{F}_x^\mathsf{T}dt)

with ![](https://latex.codecogs.com/svg.latex?\textbf{F}_x) being the Jacobian of the state dynamics derived after the error states and  ![](https://latex.codecogs.com/svg.latex?\textbf{F}_n) being the Jacobian of the state dynamics derived after the propagation sensor noise.

At the very moment, this integration is done by formulating the problem symbolically in Matlab and integrating over  ![](https://latex.codecogs.com/svg.latex?\Delta{}t). The resulting function is then exported to the C++ function that you mentioned. This function is unfortunately not directly human-readable. This will change in the next iteration.

However, and just for clarification: The core state propagation is agnostic to the update sensors. If you want to add a sensor module to MaRS then the process noise formulation remains the same.

**Comment by extr15** [comment]
Hi Chris, thanks, and looking forward to your iteration.
