### ISSUE TITLE
Asynchronous fusion of multi-sensor data

### ISSUE THREAD

**Issue by WuZihao12** [aau-cns/mars_lib#4]
Hi and thanks for your work!
I want to study an asynchronous multi-camera system, is this code suitable for the purpose, is there any relevant case?

**Comment by Chris-Bee** [comment]
@WuZihao12 Thank you!

Yes, the MaRS framework is suitable for this case. All measurements can be processed asynchronously, MaRS will handle the intermediate IMU propagation steps and possible out of order measurement updates for you. In addition, with the modularity approach that MaRS is using, the handling of asynchronous measurment inputs is handled without the usual computational overhead. I hope this helps.

**Comment by WuZihao12** [comment]
Thank you very much for your reply

**Comment by WuZihao12** [comment]
Hi, can this module be used for optimization based vio? For example, [vins-mono](https://github.com/HKUST-Aerial-Robotics/VINS-Mono) Or filter-based vio, such as [open_vins](https://github.com/rpng/open_vins).

**Comment by WuZihao12** [comment]
Hello, is this [visio](https://github.com/aau-cns/mars_lib/tree/main/source/mars/include/mars/sensors/vision)  a camera model?

**Comment by WuZihao12** [comment]
Thank you for your reply.

**Comment by Chris-Bee** [comment]
You are welcome.
